/****** Object:  Table [Master].[SOURCE_TYPE_MASTER]    Script Date: 11-05-2023 16:00:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[SOURCE_TYPE_MASTER](
	[SOURCE_TYPE_CODE] [tinyint] IDENTITY(1,1) NOT NULL,
	[SOURCE_TYPE_DESC] [varchar](512) NULL,
	[SOURCE_TYPE_KEY] [varchar](64) NULL,
	[SOURCE_TABLE] [varchar](100) NULL,
	[DESTINATION_TABLE] [varchar](100) NULL,
	[IS_ACTIVE] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[row_version] [timestamp] NOT NULL,
	[is_delete] [bit] NULL,
 CONSTRAINT [PK_SOURCE_TYPE_MASTER] PRIMARY KEY CLUSTERED
(
	[SOURCE_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_SORCE_TYPE_MASTER_SOURCE_TYPE_DESC] UNIQUE NONCLUSTERED
(
	[SOURCE_TYPE_DESC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Master].[SOURCE_TYPE_MASTER] ADD  CONSTRAINT [DF_SOURCE_TYPE_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Master].[SOURCE_TYPE_MASTER] ADD  CONSTRAINT [DF_SOURCE_TYPE_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Master].[SOURCE_TYPE_MASTER] ADD  DEFAULT ((0)) FOR [is_delete]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Source Master to know which kind of data will store to details tables' , @level0type=N'SCHEMA',@level0name=N'Master', @level1type=N'TABLE',@level1name=N'SOURCE_TYPE_MASTER'
GO