/****** Object:  Table [Master].[DOCUMENT_TYPE_MASTER]    Script Date: 11-05-2023 16:07:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Master].[DOCUMENT_TYPE_MASTER](
	[DOCUMENT_TYPE_CODE] [smallint] IDENTITY(1,1) NOT NULL,
	[DOCUMENT_TYPE_DESCRIPTION] [varchar](64) NULL,
	[IS_ACTIVE] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[row_version] [timestamp] NOT NULL,
	[is_delete] [bit] NULL,
	[DOCUMENT_TYPE_KEY] [varchar](64) NULL,
	[IS_DELETABLE] [bit] NULL,
 CONSTRAINT [PK_DOCUMENT_TYPE_MASTER] PRIMARY KEY CLUSTERED
(
	[DOCUMENT_TYPE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_DOCUMENT_TYPE_MASTER_DOCUMENT_TYPE_KEY] UNIQUE NONCLUSTERED
(
	[DOCUMENT_TYPE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [Master].[DOCUMENT_TYPE_MASTER] ADD  CONSTRAINT [DF_DOCUMENT_TYPE_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Master].[DOCUMENT_TYPE_MASTER] ADD  CONSTRAINT [DF_DOCUMENT_TYPE_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Master].[DOCUMENT_TYPE_MASTER] ADD  DEFAULT ((0)) FOR [is_delete]
GO

ALTER TABLE [Master].[DOCUMENT_TYPE_MASTER] ADD  CONSTRAINT [DF_document_type_master_IS_DELETABLE]  DEFAULT ((0)) FOR [IS_DELETABLE]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Type of document master' , @level0type=N'SCHEMA',@level0name=N'Master', @level1type=N'TABLE',@level1name=N'DOCUMENT_TYPE_MASTER'
GO