/****** Object:  Table [Sales].[EMAILS]    Script Date: 11-05-2023 16:10:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Sales].[EMAILS](
	[EMAIL_CODE] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[SOURCE_CODE] [int] NULL,
	[SOURCE_TYPE_CODE] [tinyint] NULL,
	[EMAIL_ADDRESS] [varchar](1024) NULL,
	[IS_ACTIVE] [bit] NULL,
	[IS_PRIMARY] [bit] NULL,
	[APPS_CODE] [tinyint] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [smallint] NULL,
	[CREATED_IPLOCATION_ID] [int] NULL,
	[MODIFIED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [smallint] NULL,
	[MODIFIED_IPLOCATION_ID] [int] NULL,
	[EMAIL_ADDRESS_TEST] [varchar](512) NULL,
	[SOL_EMAIL_TYPE] [varchar](max) NULL,
 CONSTRAINT [PK_EMAILS_MASTER] PRIMARY KEY CLUSTERED
(
	[EMAIL_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [Sales].[EMAILS] ADD  CONSTRAINT [DF_EMAILS_MASTER_IS_ACTIVE]  DEFAULT ((0)) FOR [IS_ACTIVE]
GO

ALTER TABLE [Sales].[EMAILS] ADD  CONSTRAINT [DF_EMAILS_MASTER_IS_PRIMARY]  DEFAULT ((0)) FOR [IS_PRIMARY]
GO

ALTER TABLE [Sales].[EMAILS] ADD  CONSTRAINT [DF_EMAILS_MASTER_CREATED_DATETIME]  DEFAULT ([Master].[Fn_GetISTDATETIME]()) FOR [CREATED_DATETIME]
GO

ALTER TABLE [Sales].[EMAILS]  WITH CHECK ADD  CONSTRAINT [FK_EMAILS_SOURCE_TYPE_MASTER] FOREIGN KEY([SOURCE_TYPE_CODE])
REFERENCES [Master].[SOURCE_TYPE_MASTER] ([SOURCE_TYPE_CODE])
GO

ALTER TABLE [Sales].[EMAILS] CHECK CONSTRAINT [FK_EMAILS_SOURCE_TYPE_MASTER]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Registered emails' , @level0type=N'SCHEMA',@level0name=N'Sales', @level1type=N'TABLE',@level1name=N'EMAILS'
GO